services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - minecraft_data:/data
    environment:
      - API_KEY=${API_KEY}
      - DATA_PATH=${HOST_DATA_PATH}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      minecraft-image-pull:
        condition: service_completed_successfully

  # Service to ensure Minecraft image is pulled
  minecraft-image-pull:
    image: itzg/minecraft-server:latest
    command: echo "Minecraft server image pulled successfully"
    deploy:
      replicas: 0
    pull_policy: always

volumes:
  minecraft_data: