version: '3.8'

services:
  ui:
    image: intecco/mboxmini-ui:latest
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:${API_PORT:-8080}
    depends_on:
      api:
        condition: service_healthy

  api:
    image: intecco/mboxmini-api:latest
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - mboxmini-data:/data
      - ./minecraft-data:${DATA_PATH:-/minecraft-data}
    environment:
      - API_KEY=${API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - DATA_PATH=${DATA_PATH:-/minecraft-data}
      - NODE_ENV=${NODE_ENV:-production}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@mboxmini.local}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      mc-image-pull:
        condition: service_completed_successfully

  # Service to ensure Minecraft image is pulled
  mc-image-pull:
    image: itzg/minecraft-server:latest
    command: echo "Minecraft server image pulled successfully"
    deploy:
      replicas: 0
    pull_policy: always

volumes:
  mboxmini-data:
