services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - API_KEY=${API_KEY}
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ./minecraft-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - minecraft

  minecraft:
    image: itzg/minecraft-server
    container_name: mboxmini-server
    environment:
      EULA: "TRUE"
      MEMORY: "${MAX_MEMORY:-2G}"
      VERSION: "${MINECRAFT_VERSION:-1.20.4}"
      TYPE: "VANILLA"
    volumes:
      - ./minecraft-data:/data
    ports:
      - "${MINECRAFT_PORT:-25565}:25565" 