services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - API_KEY=${API_KEY}
      - DATA_PATH=${HOST_DATA_PATH}
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_DATA_PATH}:/minecraft-data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_KEY=${API_KEY}
      - REACT_APP_API_URL=http://localhost:${API_PORT:-8080}
      - REACT_APP_MINECRAFT_PORT=${MINECRAFT_PORT:-25565}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api